use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

// ═══════════════════════════════════════════════════════════════════════
// Data model — corrected schema from the real database_sm64coopdx.json
// (generated by sm64coopdx_database_scraper.py). All optional fields
// have defaults via #[serde(default)] so missing keys don't fail parsing.
// ═══════════════════════════════════════════════════════════════════════

#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct ModUpdate {
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub date: Option<String>,
    #[serde(default)]
    pub changelog: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
// Used by tests and will be used from main.rs in 19b
#[allow(dead_code)]
pub struct DbMod {
    pub id: String,
    #[serde(default)]
    pub url: String,
    #[serde(default)]
    pub extracted_at: Option<String>,
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub version: Option<String>,
    #[serde(default)]
    pub author: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub is_featured: bool,
    #[serde(default)]
    pub image_url: Option<String>,
    #[serde(default)]
    pub description_images: Vec<String>,
    #[serde(default)]
    pub downloads: u64,
    #[serde(default)]
    pub views: u64,
    #[serde(default)]
    pub rating: Option<f64>,
    #[serde(default)]
    pub rating_count: u64,
    #[serde(default)]
    pub review_count: u64,
    #[serde(default)]
    pub update_count: u64,
    #[serde(default)]
    pub first_release: Option<String>,
    #[serde(default)]
    pub last_update: Option<String>,
    #[serde(default)]
    pub download_urls: Vec<String>,
    #[serde(default)]
    pub updates: Vec<ModUpdate>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct DbFile {
    #[serde(default)]
    pub generated_at: Option<String>,
    #[serde(default)]
    pub total_mods: usize,
    #[serde(default)]
    pub mods: HashMap<String, DbMod>,
    #[serde(default)]
    pub failed_urls: Vec<String>,
}

impl DbMod {
    /// Detect if any download URL points to a GameBanana page (not a direct
    /// ZIP/LUA file). These require manual scraping or redirect handling in
    /// the download step (step 23).
    #[allow(dead_code)]
    pub fn requires_manual_download(&self) -> bool {
        self.download_urls.iter().any(|u| {
            let lower = u.to_lowercase();
            lower.contains("gamebanana.com")
        })
    }
}

// ═══════════════════════════════════════════════════════════════════════
// Search index — built once after DB load, used by steps 20-21
// ═══════════════════════════════════════════════════════════════════════

/// Pre‑computed searchable text for a single mod entry.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct ModIndexEntry {
    pub mod_id: String,
    /// Concatenated id + title + author + tags + description, lowercased.
    pub searchable_text: String,
    /// Lowercase tags for precise OR matching (step 21).
    pub lower_tags: Vec<String>,
    /// Lowercase author (None if no author) for exact match (step 21).
    pub lower_author: Option<String>,
    /// Author as displayed (original casing, None if no author).
    pub author_display: Option<String>,
    /// Title as displayed (original casing, falls back to mod_id).
    pub title_display: String,
    /// Rating for default sort.
    pub rating: f64,
    /// Download count for stats display.
    pub downloads: u64,
}

/// Fully constructed search index for all mods in the database.
///
/// Built once via `build_search_index()`, then queried per‑frame during
/// search without re‑scanning the full mod list.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct SearchIndex {
    /// One entry per mod (same order as DbFile.mods iteration)
    pub entries: Vec<ModIndexEntry>,
    /// Global tag → count (across all mods). Used in step 21 to find the
    /// 9 most popular tags for chip display.
    pub tag_frequency: HashMap<String, usize>,
    /// Deduplicated, case‑preserving, alphabetically sorted author list.
    /// Used in step 21 for the author dropdown / autocomplete.
    pub authors_sorted: Vec<String>,
}

// ── Filter semantics (documented for steps 20-21, NOT implemented yet) ──
//
// Tags (chips): multi‑select OR. Each chip toggles independently; multiple
//   active chips widen results (a mod matches if ANY active tag is present).
//
// Author (dropdown): SINGLE select. Choosing a new author REPLACES any
//   previously selected author — they do NOT combine. This differs from tags.
//
// Free‑text search: independent of both, combined in AND with
//   whatever tag/author filters are active (§9.2 of prompt‑rust‑launcher.md).

/// Build the search index from a loaded DbFile.
///
/// This is called once (lazily, on first DownloadBrowser open) and caches
/// all pre‑computed searchable text, tag frequencies, and deduplicated
/// author list.
#[allow(dead_code)]
pub fn build_search_index(db: &DbFile) -> SearchIndex {
    let mut entries: Vec<ModIndexEntry> = Vec::with_capacity(db.mods.len());
    let mut tag_frequency: HashMap<String, usize> = HashMap::new();
    let mut author_map: HashMap<String, String> = HashMap::new(); // lower → first-seen
    let mut skipped_gb = 0usize;

    for (id, m) in &db.mods {
        // ═══ Step 23c: exclude GameBanana mods — they can't be downloaded directly ═══
        if m.requires_manual_download() {
            skipped_gb += 1;
            continue;
        }
        // Build searchable text
        let mut text = String::new();
        text.push_str(&id.to_lowercase());
        text.push('|');
        let title = m.title.as_deref().unwrap_or(id).to_string();
        text.push_str(&title.to_lowercase());
        text.push('|');
        if let Some(ref a) = m.author {
            text.push_str(&a.to_lowercase());
        }
        text.push('|');
        text.push_str(&m.tags.join(" ").to_lowercase());
        text.push('|');
        if let Some(ref d) = m.description {
            text.push_str(&d.to_lowercase());
        }

        // Lowercase tags for precise matching
        let lower_tags: Vec<String> = m.tags.iter().map(|t| t.to_lowercase()).collect();

        // Lowercase author for matching
        let lower_author = m.author.as_ref().map(|a| a.to_lowercase());

        let author_display = m.author.clone();

        let rating = m.rating.unwrap_or(0.0);
        let downloads = m.downloads;

        entries.push(ModIndexEntry {
            mod_id: id.clone(),
            searchable_text: text,
            lower_tags,
            lower_author,
            author_display,
            title_display: title,
            rating,
            downloads,
        });

        // Count tags
        for tag in &m.tags {
            *tag_frequency.entry(tag.to_lowercase()).or_insert(0) += 1;
        }

        // Deduplicate authors (case‑insensitive, preserve first casing seen)
        if let Some(ref author) = m.author {
            let lower = author.to_lowercase();
            author_map.entry(lower).or_insert_with(|| author.clone());
        }
    }

    // Build sorted author list
    let mut authors_sorted: Vec<String> = author_map.into_values().collect();
    authors_sorted.sort_by_key(|a| a.to_lowercase());

    if skipped_gb > 0 {
        log::info!(
            "build_search_index: excluded {} GameBanana mod(s), {} entries indexed",
            skipped_gb,
            entries.len()
        );
    }

    SearchIndex {
        entries,
        tag_frequency,
        authors_sorted,
    }
}

/// Load and parse the mod database from a JSON file.
///
/// Returns `Err` with a descriptive message if the file is missing, empty,
/// or contains invalid JSON. Does NOT panic.
#[allow(dead_code)]
pub fn load_database(path: &Path) -> Result<DbFile, String> {
    let t0 = Instant::now();

    let raw = fs::read_to_string(path)
        .map_err(|e| format!("Failed to read database file {:?}: {e}", path))?;

    let db: DbFile =
        serde_json::from_str(&raw).map_err(|e| format!("Failed to parse database JSON: {e}"))?;

    let elapsed = t0.elapsed();
    log::info!(
        "Loaded database: {} mods in {:.2}ms",
        db.mods.len(),
        elapsed.as_secs_f64() * 1000.0
    );

    Ok(db)
}

/// Filter mods by word‑AND query over the pre‑built search index.
///
/// Each word from the query must appear as a substring somewhere in the
/// mod's `searchable_text`. Returns indices into `index.entries`.
///
/// This is called from the main loop on every keystroke — the caller should
/// cache results (only recompute when the query changes).
#[allow(dead_code)]
pub fn filter_mods(index: &SearchIndex, query: &str) -> Vec<usize> {
    if query.trim().is_empty() {
        return Vec::new();
    }
    filter_mods_combined_inner(index, query, &[], None)
}

/// Combined AND filter: text (AND) + tags (OR) + author (AND).
///
/// Each filter dimension that is non‑empty/Some MUST match for a mod to be
/// included. Tags use OR semantics (any active tag is sufficient). Text
/// uses word‑AND. Author is an exact single match (None = all authors).
pub fn filter_mods_combined(
    index: &SearchIndex,
    query: &str,
    active_tags: &[String],
    active_author: Option<&str>,
) -> Vec<usize> {
    filter_mods_combined_inner(index, query, active_tags, active_author)
}

fn filter_mods_combined_inner(
    index: &SearchIndex,
    query: &str,
    active_tags: &[String],
    active_author: Option<&str>,
) -> Vec<usize> {
    let lower = query.to_lowercase();
    let words: Vec<&str> = lower.split_whitespace().collect();

    let lower_tags: Vec<String> = active_tags.iter().map(|t| t.to_lowercase()).collect();
    let lower_author = active_author.map(|a| a.to_lowercase());

    let mut results: Vec<usize> = Vec::new();
    for (i, entry) in index.entries.iter().enumerate() {
        // Text filter (AND across words)
        if !words.is_empty() && !words.iter().all(|w| entry.searchable_text.contains(w)) {
            continue;
        }
        // Tags filter (OR across active tags)
        if !lower_tags.is_empty()
            && !lower_tags
                .iter()
                .any(|t| entry.lower_tags.iter().any(|lt| lt == t))
        {
            continue;
        }
        // Author filter (exact match)
        if let Some(ref author) = lower_author
            && entry.lower_author.as_ref() != Some(author)
        {
            continue;
        }
        results.push(i);
    }
    results
}

/// Return the top N tags by frequency, sorted descending.
///
/// Use `tag_frequency` from the SearchIndex (built once). Returns at most
/// `n` entries, or fewer if the index has fewer unique tags.
pub fn top_tags(index: &SearchIndex, n: usize) -> Vec<(String, usize)> {
    let mut pairs: Vec<(String, usize)> = index
        .tag_frequency
        .iter()
        .map(|(tag, count)| (tag.clone(), *count))
        .collect();
    pairs.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
    pairs.truncate(n);
    pairs
}

/// Return authors from `authors_sorted` whose name starts with `prefix`
/// (case‑insensitive), preserving the original casing from the DB.
///
/// Returns empty Vec when prefix is empty.
pub fn autocomplete_authors(index: &SearchIndex, prefix: &str) -> Vec<String> {
    if prefix.is_empty() {
        return Vec::new();
    }
    let lower = prefix.to_lowercase();
    index
        .authors_sorted
        .iter()
        .filter(|a| a.to_lowercase().starts_with(&lower))
        .cloned()
        .collect()
}

// ═══════════════════════════════════════════════════════════════════════
// Step 23a: HTTP download
// ═══════════════════════════════════════════════════════════════════════

/// Thread‑safe download progress. The worker thread writes updates via the
/// Mutex; the main loop reads them every frame to render the progress bar.
#[derive(Debug, Clone)]
pub struct DownloadProgress {
    pub bytes: u64,
    pub total: Option<u64>,
    pub done: bool,
    pub error: Option<String>,
    pub extracted: u32, // number of mods extracted (0 if download-only)
}

impl DownloadProgress {
    pub fn new(total: Option<u64>) -> Self {
        Self {
            bytes: 0,
            total,
            done: false,
            error: None,
            extracted: 0,
        }
    }

    pub fn pct(&self) -> u8 {
        if let Some(t) = self.total
            && t > 0
        {
            return ((self.bytes * 100) / t).min(100) as u8;
        }
        if self.done { 100 } else { 0 }
    }
}

/// Parse Content‑Disposition header to extract filename.
///
/// Supports:
///   `attachment; filename="file.zip"`
///   `attachment; filename*=UTF-8''file%20name.zip`
pub fn parse_content_disposition(cd: &str) -> Option<String> {
    // Try filename*= (RFC 5987)
    if let Some(start) = cd.to_lowercase().find("filename*=") {
        let rest = &cd[start + 10..]; // after "filename*="
        // Skip encoding prefix e.g. "UTF-8''"
        let after_encoding = if let Some(pos) = rest.find("''") {
            &rest[pos + 2..]
        } else {
            rest
        };
        // Decode percent‑encoding (simple: just %20 → space)
        let decoded: String = after_encoding.trim_matches('"').replace("%20", " ");
        if !decoded.is_empty() {
            return Some(decoded);
        }
    }

    // Try filename= (plain)
    if let Some(start) = cd.to_lowercase().find("filename=") {
        let rest = &cd[start + 9..]; // after "filename="
        let name = rest.trim().trim_matches('"');
        if !name.is_empty() {
            return Some(name.to_string());
        }
    }

    None
}

/// Extract the last filename segment from a URL path.
///
/// Removes query strings and fragments; returns the final path component.
/// e.g. "https://example.com/path/to/mod.zip?v=2" → "mod.zip"
pub fn filename_from_url(url: &str) -> String {
    // Simple extraction: find last '/' before '?' or '#', take the segment after
    let stripped = url.split('?').next().unwrap_or(url);
    let stripped = stripped.split('#').next().unwrap_or(stripped);
    let segments: Vec<&str> = stripped.rsplitn(2, '/').collect();
    let name = segments[0].trim();
    if name.is_empty() {
        "download.zip".to_string()
    } else {
        name.to_string()
    }
}

/// Resolve safe download filename: Content-Disposition → URL path → fallback.
pub fn resolve_download_filename(
    url: &str,
    content_disposition: Option<&str>,
    fallback_id: &str,
) -> String {
    if let Some(cd) = content_disposition
        && let Some(name) = parse_content_disposition(cd)
    {
        return sanitize_filename(&name);
    }
    let from_url = filename_from_url(url);
    if !from_url.is_empty() && from_url != "download.zip" {
        return sanitize_filename(&from_url);
    }
    // Fallback: use mod_id with .zip extension
    format!("{}.zip", sanitize_filename(fallback_id))
}

/// Strip or replace characters unsafe for filesystem names.
fn sanitize_filename(name: &str) -> String {
    name.chars()
        .map(|c| match c {
            '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            c => c,
        })
        .collect()
}

/// Download a file from `url` into `dest_dir`, streaming to disk.
///
/// - `progress` is updated after each chunk (the main loop polls it).
/// - `cancel` is checked between chunks; if set, the download aborts and
///   the partial `.part` file is deleted.
/// - Returns the final `PathBuf` of the downloaded file on success.
pub fn download_mod_file(
    url: &str,
    dest_dir: &Path,
    filename_hint: &str,
    progress: &Arc<Mutex<DownloadProgress>>,
    cancel: &AtomicBool,
) -> Result<PathBuf, String> {
    let client = reqwest::blocking::Client::builder()
        .connect_timeout(Duration::from_secs(30))
        .timeout(None) // no total timeout — large mods take time
        .build()
        .map_err(|e| format!("Failed to create HTTP client: {e}"))?;

    let response = client
        .get(url)
        .header("User-Agent", "SM64CoopDX-Launcher/2.0")
        .send()
        .map_err(|e| {
            // Detect 404 / connection errors with a user‑friendly message
            if e.is_connect() {
                format!("Cannot connect to server for: {url}. Check your internet connection.")
            } else if e.is_timeout() {
                format!("Connection timed out downloading: {url}")
            } else {
                format!("Download failed for {url}: {e}")
            }
        })?;

    // Check HTTP status
    if !response.status().is_success() {
        return Err(format!(
            "Server returned HTTP {} for: {url}",
            response.status().as_u16()
        ));
    }

    let total_bytes = response.content_length();

    // Resolve filename
    let content_disp = response
        .headers()
        .get(reqwest::header::CONTENT_DISPOSITION)
        .and_then(|v| v.to_str().ok());
    let filename = resolve_download_filename(url, content_disp, filename_hint);

    let tmp_path = dest_dir.join(format!(".{}.part", filename));
    let final_path = dest_dir.join(&filename);

    // Ensure destination directory exists
    fs::create_dir_all(dest_dir)
        .map_err(|e| format!("Cannot create dest dir {}: {e}", dest_dir.display()))?;

    // Set initial progress
    {
        let mut p = progress.lock().map_err(|e| format!("Mutex: {e}"))?;
        p.bytes = 0;
        p.total = total_bytes;
        p.done = false;
        p.error = None;
    }

    // Stream body to disk
    let mut file = fs::File::create(&tmp_path)
        .map_err(|e| format!("Cannot create temp file {}: {e}", tmp_path.display()))?;

    let mut reader: Box<dyn Read> = Box::new(response);
    let mut buf = [0u8; 65536];
    let mut bytes_downloaded: u64 = 0;

    loop {
        // Check cancel before each chunk
        if cancel.load(Ordering::Relaxed) {
            drop(file);
            let _ = fs::remove_file(&tmp_path);
            {
                let mut p = progress.lock().map_err(|e| format!("Mutex: {e}"))?;
                p.done = true;
                p.error = Some("Download cancelled".to_string());
            }
            return Err("Download cancelled".to_string());
        }

        let n = reader
            .read(&mut buf)
            .map_err(|e| format!("Read error: {e}"))?;
        if n == 0 {
            break;
        }

        file.write_all(&buf[..n])
            .map_err(|e| format!("Write error to {}: {e}", tmp_path.display()))?;

        bytes_downloaded += n as u64;

        // Update progress every ~128KB to reduce mutex contention
        if bytes_downloaded % (128 * 1024) < n as u64 || n < 65536 {
            let mut p = progress.lock().map_err(|e| format!("Mutex: {e}"))?;
            p.bytes = bytes_downloaded;
            p.total = total_bytes;
        }
    }

    // Final progress update
    {
        let mut p = progress.lock().map_err(|e| format!("Mutex: {e}"))?;
        p.bytes = bytes_downloaded;
        p.total = total_bytes;
        p.done = true;
    }

    // Atomic rename: .part → final
    fs::rename(&tmp_path, &final_path).map_err(|e| {
        format!(
            "Failed to finalize download {} → {}: {e}",
            tmp_path.display(),
            final_path.display()
        )
    })?;

    log::info!(
        "Downloaded {} ({:.1} MB)",
        filename,
        bytes_downloaded as f64 / (1024.0 * 1024.0)
    );

    Ok(final_path)
}

// ═══════════════════════════════════════════════════════════════════════
// Step 23b: ZIP extraction
// ═══════════════════════════════════════════════════════════════════════

/// Extract a downloaded mod ZIP into `dest_root` (the mods directory).
///
/// Algorithm (per AGENTS.md "Extracción ZIP inteligente"):
/// 1. Scan all ZIP entries for files named `main.lua`.
/// 2. For each `main.lua` found, its parent directory is a **mod root**.
///    Extract all entries under that root to `dest_root/{mod_root_name}/`.
/// 3. If NO `main.lua` is found anywhere, fall back to extracting the
///    entire ZIP flat into `dest_root/`.
/// 4. Zip‑slip guard: entries with `../` or absolute paths are rejected
///    individually without aborting the rest of the extraction.
///
/// Returns a list of final mod directories (one per mod root).
pub fn extract_mod_zip(zip_path: &Path, dest_root: &Path) -> Result<Vec<PathBuf>, String> {
    let file = fs::File::open(zip_path)
        .map_err(|e| format!("Cannot open ZIP {}: {e}", zip_path.display()))?;

    let mut archive = zip::ZipArchive::new(file)
        .map_err(|e| format!("Invalid ZIP {}: {e}", zip_path.display()))?;

    // ── Pass 1: find all main.lua entries ──
    let mut main_lua_paths: Vec<String> = Vec::new();
    for i in 0..archive.len() {
        let entry = archive
            .by_index(i)
            .map_err(|e| format!("ZIP entry {i}: {e}"))?;
        let name = entry.name().to_string();
        if name.ends_with("main.lua") {
            // Normalize: remove trailing "main.lua", keep the parent directory
            let dir = if let Some(pos) = name.rfind('/') {
                &name[..pos + 1] // includes trailing /
            } else {
                ""
            };
            main_lua_paths.push(dir.to_string());
        }
    }

    // Deduplicate mod roots (multiple main.lua in same dir is same root)
    let mut mod_roots: Vec<String> = main_lua_paths;
    mod_roots.sort();
    mod_roots.dedup();

    // ── Pass 2: extract ──
    fs::create_dir_all(dest_root)
        .map_err(|e| format!("Cannot create dest dir {}: {e}", dest_root.display()))?;

    let mut extracted_dirs: Vec<PathBuf> = Vec::new();

    // Pre‑compute safe root paths for zip‑slip validation
    let dest_canon = dest_root
        .canonicalize()
        .unwrap_or_else(|_| dest_root.to_path_buf());

    if !mod_roots.is_empty() {
        // ── Mod‑root extraction (one subfolder per mod root) ──
        for root in &mod_roots {
            // Determine folder name: last meaningful segment of the root path
            let folder_name = root
                .trim_end_matches('/')
                .rsplit('/')
                .next()
                .unwrap_or("unknown");
            if folder_name.is_empty() {
                // main.lua at ZIP root → use ZIP filename as folder
                if let Some(stem) = zip_path.file_stem().and_then(|s| s.to_str()) {
                    let mod_dir = dest_root.join(stem);
                    fs::create_dir_all(&mod_dir)
                        .map_err(|e| format!("Cannot create mod dir {}: {e}", mod_dir.display()))?;
                    extracted_dirs.push(mod_dir);
                }
                continue;
            }
            let mod_dir = dest_root.join(folder_name);
            let created = !mod_dir.exists();
            if created {
                fs::create_dir_all(&mod_dir)
                    .map_err(|e| format!("Cannot create mod dir {}: {e}", mod_dir.display()))?;
            }
            if !extracted_dirs.iter().any(|d| d == &mod_dir) {
                extracted_dirs.push(mod_dir.clone());
            }
        }

        // Re‑open archive for extraction pass (entries consumed by by_index)
        let file2 = fs::File::open(zip_path).map_err(|e| format!("Cannot reopen ZIP: {e}"))?;
        let mut archive2 =
            zip::ZipArchive::new(file2).map_err(|e| format!("Invalid ZIP on re‑open: {e}"))?;

        for i in 0..archive2.len() {
            let mut entry = archive2
                .by_index(i)
                .map_err(|e| format!("ZIP entry {i}: {e}"))?;
            let entry_name = entry.name().to_string();

            if entry.is_dir() {
                continue;
            }

            // Determine which mod root this entry belongs to
            let matched_root = mod_roots
                .iter()
                .find(|r| entry_name.starts_with(r.as_str()));

            let (target_dir, rel_path) = if let Some(root) = matched_root {
                let folder_name = root
                    .trim_end_matches('/')
                    .rsplit('/')
                    .next()
                    .unwrap_or("unknown");
                let folder_name = if folder_name.is_empty() {
                    zip_path
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("unknown")
                } else {
                    folder_name
                };
                let stripped = entry_name
                    .strip_prefix(root.as_str())
                    .unwrap_or(&entry_name);
                (dest_root.join(folder_name), stripped.to_string())
            } else {
                // Entry outside any mod root — skip (it's not part of any mod)
                continue;
            };

            // Zip‑slip guard
            let resolved = target_dir.join(&rel_path);
            if !resolved.starts_with(&dest_canon) {
                log::warn!(
                    "Zip‑slip rejected: '{}' resolves outside dest_root",
                    entry_name
                );
                continue;
            }

            // Create parent directories
            if let Some(parent) = resolved.parent() {
                fs::create_dir_all(parent)
                    .map_err(|e| format!("Cannot create dir {}: {e}", parent.display()))?;
            }

            let mut out_file = fs::File::create(&resolved)
                .map_err(|e| format!("Cannot create {}: {e}", resolved.display()))?;

            // read_all avoids decompression errors from is_file() + read() pattern
            let mut buf = Vec::new();
            entry
                .read_to_end(&mut buf)
                .map_err(|e| format!("Decompress error for '{}': {e}", entry_name))?;
            out_file
                .write_all(&buf)
                .map_err(|e| format!("Write error for {}: {e}", resolved.display()))?;
        }
    } else {
        // ── Fallback: no main.lua found → extract flat ──
        let flat_dir = dest_root.to_path_buf();
        if !flat_dir.exists() {
            fs::create_dir_all(&flat_dir).map_err(|e| format!("Cannot create flat dir: {e}"))?;
        }
        extracted_dirs.push(flat_dir.clone());

        let file2 = fs::File::open(zip_path).map_err(|e| format!("Cannot reopen ZIP: {e}"))?;
        let mut archive2 =
            zip::ZipArchive::new(file2).map_err(|e| format!("Invalid ZIP on re‑open: {e}"))?;

        for i in 0..archive2.len() {
            let mut entry = archive2
                .by_index(i)
                .map_err(|e| format!("ZIP entry {i}: {e}"))?;
            let entry_name = entry.name().to_string();

            if entry.is_dir() {
                continue;
            }

            // Strip any leading directory component (extract flat)
            let rel_path = if let Some(pos) = entry_name.rfind('/') {
                &entry_name[pos + 1..]
            } else {
                &entry_name
            };

            let resolved = flat_dir.join(rel_path);
            if !resolved.starts_with(&dest_canon) {
                log::warn!(
                    "Zip‑slip rejected (flat): '{}' resolves outside dest_root",
                    entry_name
                );
                continue;
            }

            if let Some(parent) = resolved.parent() {
                fs::create_dir_all(parent)
                    .map_err(|e| format!("Cannot create dir {}: {e}", parent.display()))?;
            }

            let mut out_file = fs::File::create(&resolved)
                .map_err(|e| format!("Cannot create {}: {e}", resolved.display()))?;

            let mut buf = Vec::new();
            entry
                .read_to_end(&mut buf)
                .map_err(|e| format!("Decompress error for '{}': {e}", entry_name))?;
            out_file
                .write_all(&buf)
                .map_err(|e| format!("Write error for {}: {e}", resolved.display()))?;
        }
    }

    log::info!(
        "Extracted {} mod(s) from {}",
        extracted_dirs.len(),
        zip_path.display()
    );
    Ok(extracted_dirs)
}

// ═══════════════════════════════════════════════════════════════════════
// Step 24: installed mod detection
// ═══════════════════════════════════════════════════════════════════════

/// Normalize a string for fuzzy matching: lowercase + alphanumeric only.
/// NEVER use for display; this strips all whitespace and punctuation.
pub fn normalize(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric())
        .collect()
}

/// Persistent mapping: folder name → DB mod_id.
pub type InstalledMap = HashMap<String, String>;

/// Load the installed‑mod mapping from `launcher_downloads.json`.
/// Returns empty HashMap if the file doesn't exist or is corrupt.
pub fn load_installed_map(path: &Path) -> InstalledMap {
    match fs::read_to_string(path) {
        Ok(json) => serde_json::from_str(&json).unwrap_or_default(),
        Err(_) => HashMap::new(),
    }
}

/// Save the installed‑mod mapping to disk atomically.
pub fn save_installed_map(path: &Path, map: &InstalledMap) -> Result<(), String> {
    let tmp = path.with_extension(".tmp");
    let json = serde_json::to_string_pretty(map).map_err(|e| format!("JSON serialize: {e}"))?;
    fs::write(&tmp, &json).map_err(|e| format!("Cannot write to {}: {e}", tmp.display()))?;
    fs::rename(&tmp, path)
        .map_err(|e| format!("Cannot rename {} → {}: {e}", tmp.display(), path.display()))
}

/// Parse the `-- id:` or `-- name:` header from a `main.lua` file.
/// Returns `Some(id)` or `Some(name)` if a header is found, `None` otherwise.
fn parse_main_lua_header(path: &Path) -> Option<String> {
    let content = fs::read_to_string(path).ok()?;
    for line in content.lines().take(40) {
        let trimmed = line.trim();
        if let Some(stripped) = trimmed.strip_prefix("-- id:") {
            return Some(stripped.trim().to_string());
        }
        if let Some(stripped) = trimmed.strip_prefix("-- name:") {
            return Some(stripped.trim().to_string());
        }
    }
    None
}

/// Multi‑strategy installed‑mod detection (per AGENTS.md §9.4):
///
/// 1. **Exact normalized match** — compare `normalize(installed_folder_name)`
///    against `normalize(title)` + `normalize(mod_id)` for every entry in the
///    search index.
/// 2. **Persistent mapping** — `launcher_downloads.json` stores folder → mod_id
///    pairs from previous matches and manual assignments.
/// 3. **Auto‑map from main.lua headers** — read `-- id:` / `-- name:` from
///    each mod's `main.lua`; only accept if the match is unambiguous (≥6 chars
///    and exactly 1 result in the DB).
///
/// Returns the set of DB mod_ids that are known to be installed.
pub fn detect_installed_mods(
    installed_dirs: &[PathBuf],
    index: &SearchIndex,
    installed_map: &InstalledMap,
) -> HashSet<String> {
    let mut detected: HashSet<String> = HashSet::new();

    for dir in installed_dirs {
        let Some(folder_name) = dir.file_name().and_then(|n| n.to_str()) else {
            continue;
        };

        // ── Strategy 1: exact normalized match ──
        let norm_folder = normalize(folder_name);
        let mut found = false;
        for entry in &index.entries {
            // Match against normalized display title and mod_id
            let norm_title = normalize(&entry.title_display);
            let norm_id = normalize(&entry.mod_id);
            if norm_folder == norm_title || norm_folder == norm_id {
                detected.insert(entry.mod_id.clone());
                found = true;
                break;
            }
        }
        if found {
            continue;
        }

        // ── Strategy 2: persistent mapping ──
        if let Some(mapped_id) = installed_map.get(folder_name) {
            // Verify the mapped ID still exists in the index
            if index.entries.iter().any(|e| &e.mod_id == mapped_id) {
                detected.insert(mapped_id.clone());
                continue;
            }
        }

        // ── Strategy 3: auto‑map from main.lua headers ──
        let lua_path = dir.join("main.lua");
        if let Some(header_id) = parse_main_lua_header(&lua_path) {
            let norm_hdr = normalize(&header_id);
            // Only accept if ≥6 chars and exactly 1 unambiguous result
            if norm_hdr.len() >= 6 {
                let matches: Vec<usize> = index
                    .entries
                    .iter()
                    .enumerate()
                    .filter(|(_, e)| {
                        normalize(&e.mod_id) == norm_hdr || normalize(&e.title_display) == norm_hdr
                    })
                    .map(|(i, _)| i)
                    .collect();

                if matches.len() == 1 {
                    detected.insert(index.entries[matches[0]].mod_id.clone());
                }
            }
        }
    }

    detected
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Small fixture: 3 mods, mix of full and partial fields.
    fn fixture_json() -> &'static str {
        r#"{
          "generated_at": "2025-01-01",
          "total_mods": 3,
          "failed_urls": [],
          "mods": {
            "mod.full.1": {
              "id": "mod.full.1",
              "url": "https://mods.sm64coopdx.com/mod/full/1",
              "extracted_at": "2025-01-01T00:00:00Z",
              "title": "Full Mod",
              "version": "1.0",
              "author": "TestAuthor",
              "description": "A complete test mod",
              "tags": ["platformer", "fun"],
              "is_featured": true,
              "image_url": "https://example.com/img.png",
              "description_images": [],
              "downloads": 100,
              "views": 200,
              "rating": 4.5,
              "rating_count": 10,
              "review_count": 5,
              "update_count": 3,
              "first_release": "2024-01-01",
              "last_update": "2025-01-01",
              "download_urls": ["https://example.com/mod.zip"],
              "updates": []
            },
            "mod.minimal.2": {
              "id": "mod.minimal.2"
            },
            "mod.banana.3": {
              "id": "mod.banana.3",
              "title": "Banana Mod",
              "author": "retrofan",
              "tags": ["fun"],
              "download_urls": ["https://gamebanana.com/mods/12345"]
            }
          }
        }"#
    }

    // ── Step 24 tests ──

    #[test]
    fn normalize_lowercase_alnum_only() {
        assert_eq!(normalize("Super Mod 2024!"), "supermod2024");
        assert_eq!(normalize("Co-Op: DX"), "coopdx");
        assert_eq!(normalize("   Spaces   "), "spaces");
        assert_eq!(normalize("UPPER.lower"), "upperlower");
    }

    #[test]
    fn detect_exact_normalized_match() {
        let json = r#"{"mods": {"mod.123": {"id": "mod.123", "title": "Super Coop Mod 2024!"}, "unrelated": {"id": "unrelated", "title": "Other Mod"}}}"#;
        let db: DbFile = serde_json::from_str(json).unwrap();
        let idx = build_search_index(&db);

        // Folder named "SuperCoopMod2024" (normalized match with "Super Coop Mod 2024!")
        let tmp = std::env::temp_dir().join("sm64launcher_detect_test_1");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp.join("SuperCoopMod2024")).unwrap();
        std::fs::create_dir_all(&tmp.join("OtherRandomFolder")).unwrap();

        let dirs: Vec<PathBuf> = std::fs::read_dir(&tmp)
            .unwrap()
            .filter_map(|e| e.ok().map(|e| e.path()))
            .collect();

        let map: InstalledMap = HashMap::new();
        let detected = detect_installed_mods(&dirs, &idx, &map);

        assert!(detected.contains("mod.123"));
        assert!(!detected.contains("unrelated"));

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn detect_persistent_mapping() {
        let json = r#"{"mods": {"mod.xyz": {"id": "mod.xyz", "title": "XYZ Mod"}}}"#;
        let db: DbFile = serde_json::from_str(json).unwrap();
        let idx = build_search_index(&db);

        let tmp = std::env::temp_dir().join("sm64launcher_detect_test_2");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp.join("RandomFolderName")).unwrap();

        let dirs: Vec<PathBuf> = std::fs::read_dir(&tmp)
            .unwrap()
            .filter_map(|e| e.ok().map(|e| e.path()))
            .collect();

        let mut map: InstalledMap = HashMap::new();
        map.insert("RandomFolderName".into(), "mod.xyz".into());

        let detected = detect_installed_mods(&dirs, &idx, &map);
        assert!(detected.contains("mod.xyz"));

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn detect_from_main_lua_header() {
        let json = r#"{"mods": {"coopdx.awesome": {"id": "coopdx.awesome", "title": "Awesome Coop Mod"}, "coopdx.awesome.2": {"id": "coopdx.awesome.2", "title": "Other Awesome"}}}"#;
        let db: DbFile = serde_json::from_str(json).unwrap();
        let idx = build_search_index(&db);

        let tmp = std::env::temp_dir().join("sm64launcher_detect_test_3");
        let _ = std::fs::remove_dir_all(&tmp);
        let mod_dir = tmp.join("CustomFolder");
        std::fs::create_dir_all(&mod_dir).unwrap();

        // Write main.lua with a matching header (≥6 chars, 1 result)
        std::fs::write(
            mod_dir.join("main.lua"),
            "-- id: coopdx.awesome\nprint('hi')",
        )
        .unwrap();

        let dirs = vec![mod_dir];
        let map: InstalledMap = HashMap::new();
        let detected = detect_installed_mods(&dirs, &idx, &map);

        assert!(detected.contains("coopdx.awesome"));
        assert!(!detected.contains("coopdx.awesome.2"));

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn detect_header_ambiguous_skipped() {
        let json = r#"{"mods": {"cool.1": {"id": "cool.1", "title": "Cool Mod Alpha"}, "cool.2": {"id": "cool.2", "title": "Cool Mod Beta"}}}"#;
        let db: DbFile = serde_json::from_str(json).unwrap();
        let idx = build_search_index(&db);

        let tmp = std::env::temp_dir().join("sm64launcher_detect_test_4");
        let _ = std::fs::remove_dir_all(&tmp);
        let mod_dir = tmp.join("CustomName");
        std::fs::create_dir_all(&mod_dir).unwrap();

        // Write main.lua with "cool mod" (≥6 chars but matches BOTH entries!)
        std::fs::write(mod_dir.join("main.lua"), "-- name: Cool Mod\nprint('hi')").unwrap();

        let dirs = vec![mod_dir];
        let map: InstalledMap = HashMap::new();
        let detected = detect_installed_mods(&dirs, &idx, &map);

        // Ambiguous (2 matches) → neither should be auto‑detected
        assert!(detected.is_empty());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn save_load_installed_map_roundtrip() {
        let tmp = std::env::temp_dir().join("sm64launcher_map_test.json");
        let _ = std::fs::remove_file(&tmp);

        let mut map: InstalledMap = HashMap::new();
        map.insert("FolderA".into(), "mod.a".into());
        map.insert("FolderB".into(), "mod.b".into());

        save_installed_map(&tmp, &map).unwrap();
        let loaded = load_installed_map(&tmp);
        assert_eq!(loaded, map);

        let _ = std::fs::remove_file(&tmp);
    }

    #[test]
    fn parse_complete_mod() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let full = &db.mods["mod.full.1"];
        assert_eq!(full.title.as_deref(), Some("Full Mod"));
        assert_eq!(full.version.as_deref(), Some("1.0"));
        assert_eq!(full.author.as_deref(), Some("TestAuthor"));
        assert_eq!(full.tags, vec!["platformer", "fun"]);
        assert_eq!(full.downloads, 100);
        assert_eq!(full.rating, Some(4.5));
        assert_eq!(full.download_urls.len(), 1);
    }

    #[test]
    fn parse_minimal_mod_uses_defaults() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let min = &db.mods["mod.minimal.2"];
        assert!(min.title.is_none());
        assert_eq!(min.tags.len(), 0);
        assert_eq!(min.download_urls.len(), 0);
        assert!(!min.is_featured);
        assert_eq!(min.downloads, 0);
    }

    #[test]
    fn load_database_missing_file_returns_err() {
        let result = load_database(Path::new("/nonexistent/db.json"));
        assert!(result.is_err());
    }

    #[test]
    fn load_database_bad_json_returns_err() {
        let dir = std::env::temp_dir().join("sm64launcher_test_bad_json");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bad.json");
        fs::write(&path, "this is not json").unwrap();
        let result = load_database(&path);
        assert!(result.is_err());
    }

    #[test]
    fn requires_manual_download_detects_gamebanana() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let banana = &db.mods["mod.banana.3"];
        assert!(banana.requires_manual_download());

        let full = &db.mods["mod.full.1"];
        assert!(!full.requires_manual_download());
    }

    #[test]
    fn requires_manual_download_www_gamebanana() {
        let db: DbFile = serde_json::from_str(
            r#"{"mods": {"x": {"id": "x", "download_urls": ["https://www.gamebanana.com/dl/123"]}}}"#,
        )
        .unwrap();
        assert!(db.mods["x"].requires_manual_download());
    }

    #[test]
    fn build_search_index_searchable_text() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);

        // Find the full mod entry
        let entry = idx
            .entries
            .iter()
            .find(|e| e.mod_id == "mod.full.1")
            .unwrap();
        // Should contain lowercased id, title, author, tags, description
        assert!(entry.searchable_text.contains("mod.full.1"));
        assert!(entry.searchable_text.contains("full mod"));
        assert!(entry.searchable_text.contains("testauthor"));
        assert!(entry.searchable_text.contains("platformer"));
        assert!(entry.searchable_text.contains("fun"));
        assert!(entry.searchable_text.contains("a complete test mod"));
    }

    #[test]
    fn build_search_index_tag_frequency() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);
        // "fun" appears in mod.full.1. mod.banana.3 is excluded (GameBanana URL),
        // so count is 1, not 2.
        assert_eq!(idx.tag_frequency.get("fun"), Some(&1));
        // "platformer" only in mod.full.1 → count 1
        assert_eq!(idx.tag_frequency.get("platformer"), Some(&1));
    }

    #[test]
    fn build_search_index_authors_deduplicated() {
        let db: DbFile = serde_json::from_str(
            r#"{"mods": {
            "a": {"id": "a", "author": "RetroFan"},
            "b": {"id": "b", "author": "retrofan"},
            "c": {"id": "c", "author": "Alice"},
            "d": {"id": "d", "author": "Bob"}
          }}"#,
        )
        .unwrap();
        let idx = build_search_index(&db);

        // "RetroFan" and "retrofan" should deduplicate to 1 entry
        assert_eq!(idx.authors_sorted.len(), 3);
        assert!(
            idx.authors_sorted
                .iter()
                .any(|a| a == "RetroFan" || a == "Alice" || a == "Bob")
        );
        // Should be sorted
        let lower: Vec<String> = idx
            .authors_sorted
            .iter()
            .map(|a| a.to_lowercase())
            .collect();
        assert!(lower.is_sorted());
    }

    /// filter_mods("") returns empty — this is correct because the UI layer
    /// (DownloadBrowserState::update_filter) handles empty query by setting
    /// `filtered = None` and falling back to the full sorted list, never
    /// calling filter_mods with an empty string.
    #[test]
    fn filter_mods_empty_query_produces_empty_vec() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);
        let results = filter_mods(&idx, "");
        assert!(results.is_empty());
    }

    #[test]
    fn filter_mods_and_match() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);
        // "full mod" matches mod.full.1 but not mod.banana.3
        let results = filter_mods(&idx, "full mod");
        assert_eq!(results.len(), 1);
        let entry = &idx.entries[results[0]];
        assert_eq!(entry.mod_id, "mod.full.1");
    }

    #[test]
    fn filter_mods_no_match_returns_empty() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);
        let results = filter_mods(&idx, "nonexistent xyzzz");
        assert!(results.is_empty());
    }

    #[test]
    fn filter_mods_partial_word_match() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);
        // "platformer" is a partial substring match within mod.full.1's searchable_text
        let results = filter_mods(&idx, "platformer");
        assert_eq!(results.len(), 1);
        assert_eq!(idx.entries[results[0]].mod_id, "mod.full.1");
    }

    /// Full database load test — `#[ignore]` by default because it reads
    /// the real 33K-line JSON file. Run manually to verify parse time.
    #[test]
    #[ignore]
    fn load_real_database() {
        let path = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../assets/database_sm64coopdx.json"
        ));

        let t0 = Instant::now();
        let db = load_database(path).expect("real database must parse");
        let load_ms = t0.elapsed().as_secs_f64() * 1000.0;

        let t1 = Instant::now();
        let idx = build_search_index(&db);
        let idx_ms = t1.elapsed().as_secs_f64() * 1000.0;

        println!("── Real database metrics ──");
        println!("  Mods:         {}", db.mods.len());
        println!("  Load time:    {load_ms:.1} ms");
        println!("  Index time:   {idx_ms:.1} ms");
        println!("  Total:        {:.1} ms", load_ms + idx_ms);
        println!("  Unique tags:  {}", idx.tag_frequency.len());
        println!("  Unique authors: {}", idx.authors_sorted.len());
    }

    // ── Step 21 tests ──

    #[test]
    fn top_9_tags_by_frequency() {
        let mut tag_frequency: HashMap<String, usize> = HashMap::new();
        // 10 tags: a0-a9 with counts 0..9, then c0 with count 100
        for i in 0..10u8 {
            tag_frequency.insert(format!("a{i}"), i as usize);
        }
        tag_frequency.insert("c0".into(), 100);
        // Also add tie: two tags with same count
        tag_frequency.insert("b0".into(), 50);
        tag_frequency.insert("b1".into(), 50);

        let index = SearchIndex {
            entries: Vec::new(),
            tag_frequency,
            authors_sorted: Vec::new(),
        };

        let top = top_tags(&index, 9);
        // Should be the 9 most frequent, descending
        assert_eq!(top.len(), 9);
        assert_eq!(top[0], ("c0".to_string(), 100));
        // b0 and b1 tied at 50, sorted alphabetically within tie
        assert_eq!(top[1], ("b0".to_string(), 50));
        assert_eq!(top[2], ("b1".to_string(), 50));
        // a9 (9) ... a4 (4) = 6 items, total 9
        assert_eq!(top[3], ("a9".to_string(), 9));
        // a8, a7, a6, a5, a4 should be the remaining
        assert_eq!(top[8], ("a4".to_string(), 4));
    }

    #[test]
    fn filter_tags_or() {
        let db: DbFile = serde_json::from_str(
            r#"{"mods": {
            "m1": {"id": "m1", "title": "Foo", "tags": ["coop"]},
            "m2": {"id": "m2", "title": "Bar", "tags": ["chars"]},
            "m3": {"id": "m3", "title": "Baz", "tags": ["unrelated"]}
          }}"#,
        )
        .unwrap();
        let idx = build_search_index(&db);

        // Two active tags: m1 (coop) + m2 (chars) should both appear
        let results = filter_mods_combined(&idx, "", &["coop".into(), "chars".into()], None);
        let ids: Vec<&str> = results
            .iter()
            .map(|&i| idx.entries[i].mod_id.as_str())
            .collect();
        assert_eq!(ids.len(), 2);
        assert!(ids.contains(&"m1"));
        assert!(ids.contains(&"m2"));
    }

    #[test]
    fn filter_author_tags_text_combined_and() {
        let db: DbFile = serde_json::from_str(
            r#"{"mods": {
            "m1": {"id": "m1", "title": "Cool coop mod", "author": "Alice", "tags": ["coop"]},
            "m2": {"id": "m2", "title": "Cool coop mod", "author": "Bob",   "tags": ["coop"]},
            "m3": {"id": "m3", "title": "Cool coop mod", "author": "Alice", "tags": ["unrelated"]}
          }}"#,
        )
        .unwrap();
        let idx = build_search_index(&db);

        // Tags "coop" + Author "Alice" + Text "cool": only m1 qualifies
        let results = filter_mods_combined(&idx, "cool", &["coop".into()], Some("Alice"));
        let ids: Vec<&str> = results
            .iter()
            .map(|&i| idx.entries[i].mod_id.as_str())
            .collect();
        assert_eq!(ids, vec!["m1"]);
    }

    #[test]
    fn autocomplete_by_prefix() {
        let db: DbFile = serde_json::from_str(
            r#"{"mods": {
            "a": {"id": "a", "author": "Alice"},
            "b": {"id": "b", "author": "Bob"},
            "c": {"id": "c", "author": "Alberto"}
          }}"#,
        )
        .unwrap();
        let idx = build_search_index(&db);

        // "al" → Alice and Alberto (case‑insensitive)
        let results = autocomplete_authors(&idx, "al");
        assert_eq!(results.len(), 2);
        assert!(results.contains(&"Alberto".to_string()));
        assert!(results.contains(&"Alice".to_string()));

        // "b" → only Bob
        let results = autocomplete_authors(&idx, "b");
        assert_eq!(results, vec!["Bob"]);

        // Empty prefix → empty
        assert!(autocomplete_authors(&idx, "").is_empty());

        // No match
        assert!(autocomplete_authors(&idx, "xx").is_empty());
    }

    #[test]
    fn filter_empty_query_tag_only() {
        let db: DbFile = serde_json::from_str(
            r#"{"mods": {
            "m1": {"id": "m1", "title": "One", "tags": ["coop"]},
            "m2": {"id": "m2", "title": "Two", "tags": ["other"]}
          }}"#,
        )
        .unwrap();
        let idx = build_search_index(&db);

        // Empty query + tag "coop" → only m1
        let results = filter_mods_combined(&idx, "", &["coop".into()], None);
        assert_eq!(results.len(), 1);
        assert_eq!(idx.entries[results[0]].mod_id, "m1");
    }

    /// When all filters are empty, filter_mods_combined returns ALL mods.
    #[test]
    fn filter_no_filters_returns_all() {
        let db: DbFile = serde_json::from_str(fixture_json()).unwrap();
        let idx = build_search_index(&db);
        let results = filter_mods_combined(&idx, "", &[], None);
        assert_eq!(results.len(), idx.entries.len());
    }

    // ── Step 23a tests ──

    #[test]
    fn filename_from_url_simple() {
        assert_eq!(
            filename_from_url("https://mods.example.com/path/to/mod.zip"),
            "mod.zip"
        );
    }

    #[test]
    fn filename_from_url_with_query() {
        assert_eq!(
            filename_from_url("https://example.com/mod.zip?v=2&a=b"),
            "mod.zip"
        );
    }

    #[test]
    fn filename_from_url_no_extension() {
        assert_eq!(
            filename_from_url("https://cdn.example.com/download"),
            "download"
        );
    }

    #[test]
    fn filename_from_url_trailing_slash() {
        assert_eq!(
            filename_from_url("https://example.com/path/"),
            "download.zip" // empty segment → fallback
        );
    }

    #[test]
    fn parse_content_disposition_plain() {
        let cd = r#"attachment; filename="coop_mod.zip""#;
        assert_eq!(
            parse_content_disposition(cd),
            Some("coop_mod.zip".to_string())
        );
    }

    #[test]
    fn parse_content_disposition_utf8() {
        let cd = "attachment; filename*=UTF-8''coop%20mod.zip";
        assert_eq!(
            parse_content_disposition(cd),
            Some("coop mod.zip".to_string())
        );
    }

    #[test]
    fn parse_content_disposition_none() {
        let cd = "attachment";
        assert_eq!(parse_content_disposition(cd), None);
    }

    #[test]
    fn resolve_download_filename_cd_priority() {
        // Content-Disposition takes priority over URL
        let name = resolve_download_filename(
            "https://example.com/wrong.zip",
            Some(r#"attachment; filename="correct.zip""#),
            "fallback",
        );
        assert_eq!(name, "correct.zip");
    }

    #[test]
    fn resolve_download_filename_url_fallback() {
        // No CD → use URL path
        let name = resolve_download_filename(
            "https://cdn.example.com/Download/ModFile.zip",
            None,
            "fallback",
        );
        assert_eq!(name, "ModFile.zip");
    }

    #[test]
    fn resolve_download_filename_id_fallback() {
        // No CD, no meaningful URL segment → use mod_id
        let name = resolve_download_filename("https://example.com/", None, "my-mod");
        assert_eq!(name, "my-mod.zip");
    }

    #[test]
    fn sanitize_bad_chars() {
        let result = super::sanitize_filename("bad:file<name.>zip");
        assert_eq!(result, "bad_file_name._zip");
    }

    /// Mock server test: spawn a tiny HTTP server on localhost, serve a
    /// known payload, download it via download_mod_file, verify content.
    #[test]
    fn mock_download_small_file() {
        use std::io::Write;
        use std::net::TcpListener;
        use std::thread;

        let payload = b"Hello, this is a test mod file!\nIt has 51 bytes.";
        let payload_len = payload.len() as u64;

        // Bind to random port
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let url = format!("http://{addr}/test.zip");

        let server_thread = thread::spawn(move || {
            for stream in listener.incoming() {
                if let Ok(mut s) = stream {
                    let _ = s.write_all(
                        format!(
                            "HTTP/1.1 200 OK\r\n\
                             Content-Type: application/zip\r\n\
                             Content-Length: {payload_len}\r\n\
                             Content-Disposition: attachment; filename=\"test_mod.zip\"\r\n\
                             Connection: close\r\n\
                             \r\n"
                        )
                        .as_bytes(),
                    );
                    let _ = s.write_all(payload);
                    let _ = s.flush();
                    // Only serve one request, then stop
                    break;
                }
            }
        });

        let progress = Arc::new(Mutex::new(DownloadProgress::new(None)));
        let cancel = Arc::new(AtomicBool::new(false));
        let tmp_dir = std::env::temp_dir().join("sm64launcher_dl_test");

        let _ = std::fs::remove_dir_all(&tmp_dir);
        std::fs::create_dir_all(&tmp_dir).unwrap();

        let result = download_mod_file(&url, &tmp_dir, "fallback", &progress, &cancel);

        let _ = server_thread.join();
        let _ = std::fs::remove_dir_all(&tmp_dir);

        match result {
            Ok(path) => {
                assert!(path.file_name().unwrap() == "test_mod.zip");

                let progr = progress.lock().unwrap();
                assert!(progr.done);
                assert_eq!(progr.bytes, payload_len);
                assert!(progr.error.is_none());
            }
            Err(e) => panic!("Download should succeed but got error: {e}"),
        }
    }

    /// build_search_index() excludes mods with requires_manual_download=true.
    /// These are GameBanana page URLs, not direct ZIP archives — they can't
    /// be downloaded automatically, so they're excluded from the searchable
    /// mod list entirely (step 23c decision).
    #[test]
    fn build_search_index_excludes_gamebanana() {
        let json = r#"{"mods":{"normal":{"id":"normal","title":"Normal","download_urls":["https://mods.sm64coopdx.com/mod.zip"]},"gb1":{"id":"gb1","title":"GB1","download_urls":["https://gamebanana.com/mods/1"]},"gb2":{"id":"gb2","title":"GB2","download_urls":["https://www.gamebanana.com/dl/2"]},"normal2":{"id":"normal2","title":"N2","download_urls":["https://example.com/mod.zip"]}}}"#;
        let db: DbFile = serde_json::from_str(json).unwrap();

        let idx = build_search_index(&db);
        // Only the 2 non‑GameBanana mods should be in the index
        assert_eq!(idx.entries.len(), 2);
        let ids: Vec<&str> = idx.entries.iter().map(|e| e.mod_id.as_str()).collect();
        assert!(ids.contains(&"normal"));
        assert!(ids.contains(&"normal2"));
        assert!(!ids.contains(&"gb1"));
        assert!(!ids.contains(&"gb2"));

        // Tag frequency and author counts should NOT include excluded mods
        // (in this fixture, no tags/authors, so just verifying it doesn't panic)
        assert!(idx.tag_frequency.is_empty());
        assert!(idx.authors_sorted.is_empty());
    }

    /// Real download test — validates Content-Length match, filename
    /// resolution (via Content-Disposition), and bytes reported match
    /// file size. Requires internet access.
    #[test]
    #[ignore]
    fn real_download_small_mod() {
        let url = "https://mods.sm64coopdx.com/mods/15.681/download";
        let progress = Arc::new(Mutex::new(DownloadProgress::new(None)));
        let cancel = Arc::new(AtomicBool::new(false));
        let dest_dir = std::env::temp_dir().join("sm64launcher_real_dl_test");

        let _ = std::fs::remove_dir_all(&dest_dir);
        std::fs::create_dir_all(&dest_dir).unwrap();

        let result = download_mod_file(url, &dest_dir, "15.681", &progress, &cancel);

        let progr = progress.lock().unwrap();
        assert!(progr.done);
        assert!(progr.error.is_none(), "Download error: {:?}", progr.error);

        match result {
            Ok(path) => {
                let fname = path.file_name().unwrap().to_str().unwrap();
                assert_eq!(fname, "15.zip");

                let meta = std::fs::metadata(&path).unwrap();
                let actual_bytes = meta.len();
                assert_eq!(actual_bytes, progr.bytes);
                if let Some(total) = progr.total {
                    assert_eq!(actual_bytes, total);
                }
                println!("── Real download verified ──");
                println!("  File:  {fname}  ({actual_bytes} bytes)");
                let _ = std::fs::remove_file(&path);
            }
            Err(e) => panic!("Download failed: {e}"),
        }
        let _ = std::fs::remove_dir_all(&dest_dir);
    }

    /// Cancel test: verify no .part files remain after abort.
    #[test]
    #[ignore]
    fn real_download_cancel_cleanup() {
        let url = "https://mods.sm64coopdx.com/mods/15.681/download";
        let progress = Arc::new(Mutex::new(DownloadProgress::new(None)));
        let cancel = Arc::new(AtomicBool::new(false));
        let dest_dir = std::env::temp_dir().join("sm64launcher_cancel_test");

        let _ = std::fs::remove_dir_all(&dest_dir);
        std::fs::create_dir_all(&dest_dir).unwrap();

        cancel.store(true, Ordering::Relaxed);
        let result = download_mod_file(url, &dest_dir, "15.681", &progress, &cancel);

        let progr = progress.lock().unwrap();
        assert!(progr.error.is_some());
        assert!(result.is_err());

        let entries: Vec<_> = std::fs::read_dir(&dest_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .collect();
        assert!(entries.is_empty(), "Expected empty dir after cancel");
        println!("── Cancel cleanup verified ──");
        let _ = std::fs::remove_dir_all(&dest_dir);
    }

    // ── Step 23b tests ──

    /// Build an in‑memory ZIP and write it to `path`.
    fn build_test_zip(path: &Path, entries: &[(&str, &[u8])]) {
        let file = std::fs::File::create(path).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        let opts = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Deflated);
        for (name, data) in entries {
            writer.start_file(*name, opts).unwrap();
            writer.write_all(data).unwrap();
        }
        writer.finish().unwrap();
    }

    #[test]
    fn extract_finds_single_mod_root() {
        let tmp = std::env::temp_dir().join("sm64launcher_zip_test_1");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let zip_path = tmp.join("mod.zip");
        build_test_zip(
            &zip_path,
            &[
                ("super_mod/main.lua", b"-- Super Mod\n"),
                ("super_mod/script.lua", b"print('ok')\n"),
                ("super_mod/assets/tex.png", b"PNGfake"),
                ("readme.txt", b"top-level file"),
            ],
        );

        let dest = tmp.join("mods");
        let result = extract_mod_zip(&zip_path, &dest).unwrap();
        assert_eq!(result.len(), 1);
        assert!(result[0].ends_with("super_mod"));

        // Verify files exist
        assert!(dest.join("super_mod/main.lua").exists());
        assert!(dest.join("super_mod/script.lua").exists());
        assert!(dest.join("super_mod/assets/tex.png").exists());
        // readme.txt at zip root should NOT be extracted (outside mod root)
        assert!(!dest.join("super_mod/readme.txt").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn extract_finds_multiple_mod_roots() {
        let tmp = std::env::temp_dir().join("sm64launcher_zip_test_2");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let zip_path = tmp.join("multi.zip");
        build_test_zip(
            &zip_path,
            &[
                ("mod_a/main.lua", b"-- Mod A\n"),
                ("mod_a/data.lua", b"return {}\n"),
                ("nested/mod_b/main.lua", b"-- Mod B\n"),
                ("nested/mod_b/info.txt", b"hello\n"),
            ],
        );

        let dest = tmp.join("mods");
        let result = extract_mod_zip(&zip_path, &dest).unwrap();
        assert_eq!(result.len(), 2);

        // Both mod dirs should exist
        assert!(dest.join("mod_a/main.lua").exists());
        assert!(dest.join("mod_a/data.lua").exists());
        assert!(dest.join("mod_b/main.lua").exists());
        assert!(dest.join("mod_b/info.txt").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn extract_falls_back_when_no_main_lua() {
        let tmp = std::env::temp_dir().join("sm64launcher_zip_test_3");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let zip_path = tmp.join("no_lua.zip");
        build_test_zip(
            &zip_path,
            &[
                ("data/script.lua", b"-- not main\n"),
                ("data/readme.txt", b"info\n"),
                ("top_level.txt", b"hello\n"),
            ],
        );

        let dest = tmp.join("flat_out");
        let result = extract_mod_zip(&zip_path, &dest).unwrap();
        assert_eq!(result.len(), 1); // flat dir

        // Files should be extracted flat
        assert!(dest.join("script.lua").exists());
        assert!(dest.join("readme.txt").exists());
        assert!(dest.join("top_level.txt").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn extract_rejects_zip_slip() {
        let tmp = std::env::temp_dir().join("sm64launcher_zip_test_4");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let zip_path = tmp.join("slip.zip");
        build_test_zip(
            &zip_path,
            &[
                ("safe_mod/main.lua", b"-- Safe\n"),
                ("safe_mod/ok.txt", b"ok\n"),
                // Zip‑slip attempt: path traversal
                ("safe_mod/../../../etc/evil.txt", b"bad\n"),
                // Absolute path attempt
                ("safe_mod//etc/passwd", b"bad\n"),
            ],
        );

        let dest = tmp.join("mods_out");
        let result = extract_mod_zip(&zip_path, &dest).unwrap();
        assert_eq!(result.len(), 1);

        // Safe files extracted
        assert!(dest.join("safe_mod/main.lua").exists());
        assert!(dest.join("safe_mod/ok.txt").exists());

        // Zip‑slip entries must NOT exist anywhere under dest
        assert!(!dest.join("etc/evil.txt").exists());
        assert!(!dest.join("../../../etc/evil.txt").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    /// End-to-end pipeline test: download a real mod -> extract -> detect.
    /// Verifies that the installed detection recognizes the mod without
    /// manual intervention. Requires internet access.
    #[test]
    #[ignore]
    fn e2e_real_mod_download_extract_detect() {
        let url = "https://mods.sm64coopdx.com/mods/15.681/download";
        let progress = Arc::new(Mutex::new(DownloadProgress::new(None)));
        let cancel = Arc::new(AtomicBool::new(false));
        let e2e_root = std::env::temp_dir().join("sm64launcher_e2e_test");

        let _ = std::fs::remove_dir_all(&e2e_root);
        std::fs::create_dir_all(&e2e_root).unwrap();

        let dl_dir = e2e_root.join("_downloads");
        std::fs::create_dir_all(&dl_dir).unwrap();
        let mods_dir = e2e_root.join("mods");

        // Download
        let zip_path = download_mod_file(url, &dl_dir, "15.681", &progress, &cancel).unwrap();
        let progr = progress.lock().unwrap();
        assert!(progr.done);
        assert!(progr.error.is_none());
        assert_eq!(progr.bytes, 649_293);
        println!("  Download: OK");

        // Extract
        let extracted = extract_mod_zip(&zip_path, &mods_dir).unwrap();
        let _ = std::fs::remove_file(&zip_path);
        assert_eq!(extracted.len(), 1);
        let mod_dir = &extracted[0];
        assert!(mod_dir.join("main.lua").exists());
        println!("  Extract: OK -> {}", mod_dir.display());

        // Detect
        let db_path = Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../assets/database_sm64coopdx.json"
        ));
        let db = load_database(db_path).unwrap();
        let idx = build_search_index(&db);

        let installed_dirs: Vec<PathBuf> = std::fs::read_dir(&mods_dir)
            .unwrap()
            .filter_map(|e| e.ok().map(|e| e.path()))
            .collect();

        let detected = detect_installed_mods(&installed_dirs, &idx, &HashMap::new());

        assert!(
            !detected.is_empty(),
            "Expected at least one detected mod, got none"
        );
        println!(
            "  Detect: OK — {} installed mod(s) detected:",
            detected.len()
        );
        for id in &detected {
            let title = idx
                .entries
                .iter()
                .find(|e| &e.mod_id == id)
                .map(|e| e.title_display.as_str())
                .unwrap_or("?");
            println!("    {} (title: {title})", id);
        }

        let _ = std::fs::remove_dir_all(&e2e_root);
    }
}
