use std::path::PathBuf;
use std::sync::LazyLock;

fn assets_dir() -> PathBuf {
    dirs::data_dir()
        .expect("XDG data dir not available")
        .join("sm64coopdx")
        .join("assets")
}

pub static FONT_PATH: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("fonts").join("SuperMario256.ttf"));

pub static SPLASH_PNG: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("splash.png"));
pub static VINYL_PNG: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("vinyl_disc.png"));
pub static LOGO_PNG: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("sm64coopdx").join("logo.png"));
pub static ICON_PNG: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("sm64coopdx").join("icon.png"));
pub static BACKGROUND_PNG: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("background.png"));
pub static NAV_WAV: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("sounds").join("navigation_sound.wav"));
pub static SPLASH_WAV: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("sounds").join("splash_sound.wav"));
pub static OGG_DIR: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("ogg-sounds"));

pub static DATABASE_JSON: LazyLock<PathBuf> =
    LazyLock::new(|| assets_dir().join("database_sm64coopdx.json"));

pub const WINDOW_W: u32 = 1280;
pub const WINDOW_H: u32 = 720;

pub const BG_R: u8 = 20;
pub const BG_G: u8 = 10;
pub const BG_B: u8 = 60;

#[allow(dead_code)]
pub const TEXT_R: u8 = 200;
#[allow(dead_code)]
pub const TEXT_G: u8 = 160;
#[allow(dead_code)]
pub const TEXT_B: u8 = 255;

pub const PROGRESS_R: u8 = 160;
pub const PROGRESS_G: u8 = 100;
pub const PROGRESS_B: u8 = 240;

pub const FONT_SIZE_DEFAULT: u16 = 42;
pub const FONT_SIZE_MEDIUM: u16 = 28;
pub const FONT_SIZE_SMALL: u16 = 18;

pub const SPLASH_MIN_MS: u64 = 3000;
pub const FADE_DURATION_MS: u64 = 500;

pub const ROM_MD5: &str = "20b854b239203baf6c961b850a4a51a2";
pub const ROM_FILENAME: &str = "baserom.us.z64";
pub const GAME_STDERR_LOG: &str = "game_stderr.log";

pub const PROGRESS_BAR_W: u32 = 200;
pub const PROGRESS_BAR_H: u32 = 4;

// ── Download database schema warning ──────────────────────────────────
//
// The real `assets/database_sm64coopdx.json` (~33K lines, 1,122 mods) was
// generated by sm64coopdx_database_scraper.py and contains richer data than
// the DbMod struct defined in prompt‑rust‑launcher.md §13.
//
// Fields in the real JSON NOT in the spec's DbMod:
//   url, extracted_at, is_featured, image_url, description_images,
//   views, review_count, update_count, first_release, updates[]
//
// WARNING: some download_urls point to GameBanana mod PAGES, not to direct
// ZIP archives. These mods (requires_manual_download=true in DbMod) are
// excluded from SearchIndex during build_search_index() (step 23c).
// Decision: no pass-through download support for GameBanana — users must
// download these mods manually from the site.
